= Чувак, где мой сервис?
Nguyen Viet <inbox@dev-forge.ru>
:toc:

== Введение


=== Представиться

Привет!

Меня зовут Вьет, я разработчик из Альфа-Лаборатории, занимаюсь внутренним API.


=== Постановка проблемы

Мы применяем микросервисный подход к проектированию наших приложений. Базовая идея микросервисов заключается в том, что мы разбиваем наш монолитный API на множество компонентов.

Такие изолированные компоненты проще разрабатывать, но это достигается ценой усложнения поддержки всей системы в целом.

Самым очевидным следствием такого подхода является то, что вызовы методов перестают быть в пределах одного приложения. Появляется много межсервисного взаимодействия, которое порождает кучу вопросов:

1. Как обратиться к нужному сервису? Где он крутится?
2. Как распределять нагрузку между приложениями? Микросервисы дают возможность масштабировать отдельные компоненты системы в зависимости от требований нагрузки или отказоустойчивости.
3. И наконец, нетривиальный вопрос - как обновить отдельный сервис без недоступности всей системы? Мы имеем возможность независимо эволюционировать отдельные куски нашего API, но как сделать так, чтобы зависящие от них сервисы не пострадали в runtime?


=== Структура доклада

За последний год мы использовали у себя в production различные способы решения этих вопросов. Я расскажу вам о проблемах, с которыми мы столкнулись при построении server side service discovery и load balancing для наших приложений. Также мы используем на отдельном проекте client-side методы, но о них расскажут мои коллеги на другом докладе.

Мы затронем следующие технологии:

- consul [registrator/consul-template]
- mesos/marathon
- bamboo
- marathon-lb
- traefik

То, о чем дальше пойдет речь ни в коем случае не является ...

WARNING: expand


== Стек Consul


