- hosts: docker
  become: yes
  roles:
    - docker


- hosts: consul
  become: yes
  roles:
    - consul
    - registrator 
    - nginx
    - consul-template


- hosts: mesos
  become: yes
  roles:
    - { role: zookeeper-mesos-marathon, tags: zmm }


- hosts: haproxy
  become: yes
  roles:
    - { role: bamboo, tags: bamboo }
    - { role: marathon-lb, tags: mlb }
