- hosts: docker
  become: yes
  roles:
    - docker


- hosts: consul
  become: yes
  roles:
    - consul
    - registrator 
    - nginx
    - consul-template
  tags: consul


- hosts: mesos
  become: yes
  roles:
    - zookeeper-mesos-marathon
  tags: zmm


- hosts: haproxy
  become: yes
  roles:
    - { role: bamboo, tags: bamboo }
    - { role: marathon-lb, tags: mlb }
  tags: haproxy
