- hosts: vm1
  become: yes
  tasks:
    - name: start apps
      docker_container:
        name: app-{{ item }}
        image: 0x06065a/joker2016-sample-api:0.0.10
        ports:
          - "2808{{ item }}:8080"
        env:
          SERVICE_NAME: "app"
          SERVICE_CHECK_HTTP: "/health"
          SERVICE_CHECK_INTERVAL: 3s
          JOB_LENGTH_MILLIS: 0
      with_sequence: count=2

- hosts: mesos
  tasks:
    - name: start apps
      uri: 
        url: "http://{{ ansible_eth1.ipv4.address }}:8080/v2/apps?force=true"
        method: PUT
        body: "{{ lookup('template','templates/app-manifest.json.j2') }}"
        body_format: json
