- hosts: docker
  become: yes
  roles:
    - docker


- hosts: consul
  become: yes
  roles:
    - consul
    - registrator 
    - nginx
    - consul-template


- hosts: mesos
  become: yes
  roles:
    - zookeeper-mesos-marathon


- include: play-apps.yml
