- hosts: consul
  become: yes
  roles:
    - docker
    - consul
    - registrator 
    - nginx
    - consul-template

- hosts: mesos
  become: yes
  roles:
    - { role: zookeeper-mesos-marathon, tags: zmm }

- include: play-apps.yml
