- hosts: consul
  become: yes
  tasks:
    - name: start apps
      docker_container:
        name: app-{{ item }}
        image: 0x06065a/joker2016-sample-api:0.0.5
        ports:
          - "2808{{ item }}:8080"
        env:
          SERVICE_NAME: "app"
          SERVICE_CHECK_HTTP: "/health"
          SERVICE_CHECK_INTERVAL: 3s
      with_sequence: count=3
