# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/trusty64"

  config.vm.provider "virtualbox" do |v|
    v.memory = 1536 
    v.cpus = 2
  end

  config.vm.define "vm1" do |vm1|
    vm1.vm.network "private_network", ip: "192.168.5.2"
  end

  config.vm.define "vm2" do |vm2|
    vm2.vm.network "private_network", ip: "192.168.5.3"
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "play-site.yml"
    ansible.groups = {
      "consul" => ["vm1", "vm2"],
      "mesos" => ["vm2"]
    }
  end

end
